spring:
  application:
    name: springairag
  datasource:
    url: jdbc:postgresql://localhost:5432/ics
    username: postgres
    password: postgres
  sql:
    init: 
      mode: always
      schema-locations: classpath:schema.sql
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4
  vectorstore:
    pgvector:
    index-type: HNSW
    distance-type: COSINE_DISTANCE
    dimensions: 1536
    max-document-batch-size: 10000 # Optional: Maximum number of documents per batch